version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_DATABASE: News_Update_Aggregator
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

  news-fetcher-service:
    build: news-fetcher-service
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Root
      - DATABASE_NAME=News_Update_Aggregator
    volumes:
      - ./news-fetcher-service/config.yaml:/app/config.yaml
      - dapr_components:/components
    networks:
      - app-network

  news-fetcher-service-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "news-fetcher-service",
      "--app-port", "5000",
      "--placement-host-address", "placement:50006",
      "--resources-path", "/components"
    ]
    volumes:
      - dapr_components:/components
    depends_on:
      - news-fetcher-service
    network_mode: "service:news-fetcher-service"

  user-service:
    build: user-service
    ports:
      - "5001:5001"
      - "3500:3500"
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Root
      - DATABASE_NAME=News_Update_Aggregator
    volumes:
      - ./user-service/config.yaml:/app/config.yaml
      - dapr_components:/components
    networks:
      - app-network

  user-service-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "user-service",
      "--app-port", "5001",
      "--placement-host-address", "placement:50006",
      "--resources-path", "/components"
    ]
    volumes:
      - dapr_components:/components
    depends_on:
      - user-service
    network_mode: "service:user-service"

  news-aggregator-service:
    build: news-aggregator-service
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Root
      - DATABASE_NAME=News_Update_Aggregator
    volumes:
      - ./news-aggregator-service/config.yaml:/app/config.yaml
      - dapr_components:/components
    networks:
      - app-network

  news-aggregator-service-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "news-aggregator-service",
      "--app-port", "5002",
      "--placement-host-address", "placement:50006",
      "--resources-path", "/components"
    ]
    volumes:
      - dapr_components:/components
    depends_on:
      - news-aggregator-service
    network_mode: "service:news-aggregator-service"

  notification-service:
    build: notification-service
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Root
      - DATABASE_NAME=News_Update_Aggregator
    volumes:
      - ./notification-service/config.yaml:/app/config.yaml
      - dapr_components:/components
    networks:
      - app-network

  notification-service-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "notification-service",
      "--app-port", "5003",
      "--placement-host-address", "placement:50006",
      "--resources-path", "/components"
    ]
    volumes:
      - dapr_components:/components
    depends_on:
      - notification-service
    network_mode: "service:notification-service"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - app-network

volumes:
  dapr_components:
    driver: local
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge